Document: godville
Title: Debian godville Manual
Author: <insert document author here>
Abstract: This manual describes what godville is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/godville/godville.sgml.gz

Format: postscript
Files: /usr/share/doc/godville/godville.ps.gz

Format: text
Files: /usr/share/doc/godville/godville.text.gz

Format: HTML
Index: /usr/share/doc/godville/html/index.html
Files: /usr/share/doc/godville/html/*.html
